language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - docker run --rm -d -p 9867:27017 --name test_mongo mongo
  - docker run --rm -d -p 9877:5672 --name=test_rabbitmq rabbitmq
  - pytest --cov-report term --cov=brainstorm
  - docker stop test_mongo
  - docker stop test_rabbitmq
after_success:
  - codecov