FROM python:3.8-slim-buster

ADD requirements.txt /requirements.txt
RUN pip3.8 install -r requirements.txt

ADD scripts/wait-for-it.sh /wait-for-it.sh
ADD brainstorm /brainstorm

RUN apt-get update
RUN apt-get install -y npm
RUN npm install -g npm@latest

WORKDIR brainstorm/gui/gui-app
RUN npm install
RUN npm run build
WORKDIR /

EXPOSE 8080